development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: lead_capture
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: lead_capture_prod
  pool: 5
  username: root
  password: root
  host: localhost

